aws_region		= "us-east-1"
db_instance_class	= "db.t2.medium"
dbname			= "<your_db_name>"
dbuser			= "<your_db_user>"
dbpassword		= "<your_db_user_pw>"
final_snapshot_id       = "<your_snapshot_id>"
key_name		= "<your_key_name>"
public_key_path		= "<your_key_path>"
web_instance_type	= "t2.medium"
web_ami   	        = "ami-c998b6b2"
worker_instance_type    = "t2.medium"
worker_ami              = "ami-2452275e"

